name: Publish Release Artifacts

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: bellsoft/liberica-openjdk-debian:25

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Maven
        run: |
          MAVEN_VERSION=3.9.9
          curl -fsSL https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz | tar -xz -C /opt
          echo "/opt/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Build with Maven
        run: mvn -B clean package -DskipTests

      - name: Upload JAR to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/*.jar
          asset_name: app.jar
          tag: ${{ github.event.release.tag_name }}
          overwrite: true